server:
    port: 8090
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:file:/data/ryanair
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true